<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <IsContract>true</IsContract>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
    </PropertyGroup>
    <ItemGroup>
        <ContractCode Include="..\..\protobuf\awaken_points_contract_impl.proto">
            <Link>Protobuf\Proto\awaken_points_contract_impl.proto</Link>
        </ContractCode>
        <ContractBase Include="..\..\protobuf\acs12.proto">
            <Link>Protobuf\Proto\acs12.proto</Link>
        </ContractBase>
        <ContractBase Include="..\..\protobuf\acs2.proto">
            <Link>Protobuf\Proto\acs2.proto</Link>
        </ContractBase>
        <ContractBase Include="..\..\protobuf\transaction_fee.proto">
            <Link>Protobuf\Proto\reference\transaction_fee.proto</Link>
        </ContractBase>
        <ContractBase Include="..\..\protobuf\authority_info.proto">
            <Link>Protobuf\Proto\reference\authority_info.proto</Link>
        </ContractBase>
        <ContractBase Include="..\..\protobuf\request_interface.proto">
            <Link>Protobuf\Proto\request_interface.proto</Link>
        </ContractBase>
        <ContractBase Include="..\..\protobuf\awaken_points_contract.proto">
            <Link>Protobuf\Proto\awaken_points_contract.proto</Link>
        </ContractBase>
        <ContractReference Include="..\..\protobuf\acs0.proto">
            <Link>Protobuf\Proto\reference\acs0.proto</Link>
        </ContractReference>
        <ContractReference Include="..\..\protobuf\points_contract.proto">
            <Link>Protobuf\Proto\reference\points_contract.proto</Link>
        </ContractReference>
        <ContractReference Include="..\..\protobuf\token_contract.proto">
            <Link>Protobuf\Proto\reference\token_contract.proto</Link>
        </ContractReference>
        <ContractReference Include="..\..\protobuf\awaken_hooks_contract.proto">
            <Link>Protobuf\Proto\reference\awaken_hooks_contract.proto</Link>
        </ContractReference>
        <CommonMessage Include="..\..\protobuf\oracle_common_message.proto">
            <Link>Protobuf\Proto\reference\oracle_common_message.proto</Link>
        </CommonMessage>
        <ContractReference Include="..\..\protobuf\oracle_contract.proto">
            <Link>Protobuf\Proto\reference\oracle_contract.proto</Link>
        </ContractReference>
    </ItemGroup>
</Project>
